import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "~/components/common/Header";
import SessionWrapper from "~/components/Layout/SessionWraper";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <SessionWrapper>
          <Providers>
            <Header />
            {children}
          </Providers>
        </SessionWrapper>
      </body>
    </html>
  );
}
